version: '3'

services:
  api:
    build:
      context: ./backend/
    environment:
      - API_PORT
    volumes:
      - ./:/app/:rw
    ports:
      - $API_PORT:$API_PORT

  frontend:
    build:
      context: ./frontend/
    environment:
      - UI_PORT
    volumes:
      - './frontend/src:/frontend/src'
    ports:
      - $UI_PORT:8080